### PR TITLE
Start the python server when the window opens

### PR DESCRIPTION
**Pull request by calebeby**

### CODE REVIEW

**Comment by ErikBoesen** [comment]
I had been trying to figure this out for so long. Thank you so much!

**Comment by calebeby** [comment]
Potential downsides: if you type npm start, and then the window opens, and then you close it, npm start stays open because of python until you kill it.

**Comment by ErikBoesen** [comment]
That is normal on OS X, even if nothing else is running. Are you seeing that behavior on Windows?

**Comment by calebeby** [comment]
On linux, I am seeing it. I don't have access to windows right now

**Comment by ErikBoesen** [comment]
Hmm, odd.

**Pull request merged**
