### PR TITLE
Fix "window not defined" Startup Error

### PR DESCRIPTION
**Pull request by Chris2fourlaw**
Probably just a typo, this will fix the startup error

### CODE REVIEW

**Comment by Chris2fourlaw** [comment]
Looking back at this...
You may want this to be window. Ping me if it should be that way

**Comment by ErikBoesen** [comment]
I'd concur with the `window` name.

**Comment by Chris2fourlaw** [comment]
Not sure how to get it to work that way, electron works with `mainWindow` but not `window`

**Comment by ErikBoesen** [comment]
Huh, odd. This is fine then, I guess.

**Pull request merged**
