### PR TITLE
Fixed Startup Error

### PR DESCRIPTION
**Pull request by Chandi-95**

### CODE REVIEW

**Comment by ErikBoesen** [comment]
This is all your team's changes. I only want that one line fixed, not your whole dashboard.

**Comment by Chandi-95** [comment]
Uh... We couldn't exactly figure out how to open up a pull request with only one commit.

**Comment by ErikBoesen** [comment]
I'd recommend you fork to your own account and make that change there, or make a different branch with only changes from upstream.

**Comment by ErikBoesen** [comment]
#57 will replace this.

**Pull request closed without merging**
