### PR TITLE
Replace Python dependency with Node package and add build script

### PR DESCRIPTION
**Pull request by rakusan2**
In this change I had:
* Replaced the pynetworktables2js module with my own [wpilib-nt-client](https://www.npmjs.com/package/wpilib-nt-client) package
    * It has been replaced in souch a way that running the application through the browser with pynetworktables2js is still possible
* Added a connect popup which shows when the client is disconnected
    * It can be dismissed with double Esc
* Added a build script which will enable people to install it on their or similar system
    * As of now this disables easy access to the files after build

### CODE REVIEW

**Comment by andrewda** [comment]
Assuming this works just as reliably as `pynetworktables`, I'm all for this. I very much dislike spawning subprocesses (which is pretty hacky at times), and this removes the need. I can test this in a bit, probably tomorrow.

**Comment by rakusan2** [comment]
I currently do not have access to a bot so I have tested it with only a simulator but only the init method since I can not get the simulator to do anything else.
If you find an error than please message me

**Comment by atf1999** [comment]
This seems really useful

**Comment by ErikBoesen** [comment]
I'm happy to merge this if you unbundle it from TypeScript, which we decided against if I remember correctly.

**Comment by ErikBoesen** [comment]
I'm happy to merge this if you unbundle it from TypeScript, which we decided against if I remember correctly.

**Pull request closed without merging**
