### PR TITLE
replace electron-builder with electron packager

### PR DESCRIPTION
**Pull request by rakusan2**
As I mentioned in issue #30,
The new electron-builder would bring back the python dependency so I had replaced it with electron-packager.
This does not output a single executable unless you are on a mac but enables cross compilation with the exception that only windows can create the windows exe unless you are using homebrew or wine.
In this update I had also changed the file organization to better show how the files relate to each other as well to as well as to solve an issue where the packager required the main file to be in subdirectory within the project.
Another thing I had done is to up the minor version and remove the v since this project received lots of updates since the original 2.0.0 and the packager does not seem to like the version number starting with a v

### CODE REVIEW

**Comment by ErikBoesen** [comment]
I don't think it's common practice to capitalize directories like this.

**Comment by ErikBoesen** [comment]
This looks alright, but I don't like how you've moved everything into the App directory. Not to mention that I don't think capitalizing directories and naming scripts with camel case is good practice.

**Comment by ErikBoesen** [comment]
This looks fine otherwise.

**Comment by rakusan2** [comment]
Changing the name is easy so I do not have a problem of changing it

**Comment by rakusan2** [comment]
As I have seen, most large projects have their source code in a separate directory for organization purposes and when using something like VS Code it does look more organized since you can separate that which runs inside the window from what runs in electron itself from what describes the application without having them mix together

This is the current organization:
* App
  * Window
    * networktables
      * networktables.js
    * css
      * styles.css
    * ui.js
    * tryIPC.js
  * main.js
* images
  * (Images in README)
* README.md
* package.json

**Comment by ErikBoesen** [comment]
Atom doesn't do this. VSCode is an exception to most rules since it doesn't use vanilla JavaScript.

**Comment by rakusan2** [comment]
This is the project in Atom 
image

**Comment by ErikBoesen** [comment]
No, I mean the literal Atom project. github.com/atom/atom. They have top-level directories for `script`, `static`, etc.

**Comment by ErikBoesen** [comment]
Also, it's worth mentioning that this project is nowhere near as huge as those text editors, and thus doesn't need the same level of subcategorization.

**Comment by rakusan2** [comment]
It is true that I got this Atom from https://atom.io/ but should that not be the same thing as what you get from https://github.com/atom/atom

**Comment by ErikBoesen** [comment]
The literal Atom project. The code which was used to build the Atom text editor. It uses the organizational system I have just outlined. I am not referring in any way to what projects look like when opened in Atom. I'm referring to the source of Atom itself.

**Comment by rakusan2** [comment]
That project has its main in ./src/main-process/main.js which is not something I would recommend for this project since the path relation between ui.js and networktables.js will need to remain the same if you want to keep the function of running this in the browser using python.

So if you have a problem with this organization than we have three options. 
Either we remove just the window directory, or we flatten it completely to its previous state and disable the electron-packager, or we we get rid of the functionality of running it through the browser and you propose a different way to organize the files since separating that which runs in the window from that which runs outside of it will let people know that they run in different instances.

**Comment by ErikBoesen** [comment]
Why would a total flattening necessitate disabling `electron-packager`?

**Comment by rakusan2** [comment]
For some reason it requires main to be in a sub directory

**Comment by ErikBoesen** [comment]
Huh, that's odd. My recommendation would be to put the necessary files in `src/` and get rid of `window`.

**Comment by rakusan2** [comment]
Are you thinking this?
* src
  * networktables
    * networktables.js
  * css
    * styles.css
  * ui.js
  * tryIPC.js
  * main.js
* images
  * (Images in README)
* README.md
* package.json

**Comment by ErikBoesen** [comment]
Yeah.

**Comment by rakusan2** [comment]
I am also able to flatten it like so if you want:
* window
  * networktables
    * networktables.js
  * css
    * styles.css
  * ui.js
  * tryIPC.js
* src
  * main.js
* images
  * (Images in README)
* README.md
* package.json

**Comment by ErikBoesen** [comment]
Putting `window` under `src` would make more sense.

**Comment by rakusan2** [comment]
i had reorganized it as you wanted

**Comment by ErikBoesen** [comment]
Should `components` be inside the `src` directory?

**Comment by rakusan2** [comment]
Till now is has only held an empty `.keep` file so I did not know what it was meant to be used for and just left it where it was.
Therefore go ahead and move it where you want it to be

**Pull request merged**
