### PR TITLE
Add error handling on pynetworktables2js not found and change to typescript

### PR DESCRIPTION
**Pull request by rakusan2**
I have separated the loading of the server and main window, added error handling for if the pynetworktables2js module is not found and changed the main file to typescript to ensure that the correct arguments are being passed

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Hmm. I definitely do like the error handling -- it's something I've been wanting to do for a while but haven't had time -- but I'm not so sure about TypeScript. Can you run me through what your desired benefits are? (I know what TypeScript is and what it's for; I just don't know if it's worth complicating things.)

**Comment by rakusan2** [comment]
Its purpose is to ensure that you do not have spelling mistakes in your names, that you send the correct number of arguments and that those arguments are of the type which the function can use

**Comment by ErikBoesen** [comment]
Okay, that's reasonable. Can you please modify the README to contain the appropriate instructions for use with TypeScript?

**Comment by rakusan2** [comment]
I am currently changing ui to typescript and then I will update the README

**Comment by rakusan2** [comment]
In the ui.js I have noticed that you are using `NetworkTables.setValue` while the NetworkTables documentation uses `NetworkTables.putValue()`,
Is that intentional?

**Comment by ErikBoesen** [comment]
Oh yes, I've been wanting to fix that but didn't remember.

So I'm not totally sure if I want to merge this. I like TypeScript and if it was my choice, I'd definitely support translating it. However, far more people know JS than TS, so I don't know if I want to force this.

**Comment by rakusan2** [comment]
TS is just the latest version of JS with types.
For most of the code it tracks the types automatically without them being explicitly stated.
So if people just continue to write JS into the TS files than everything will still work.

Also it is common to find TS files being written without ending semicollens since the transpiler is able to add them

**Comment by ErikBoesen** [comment]
I know, it's not that it's hard, but my concern is that people will not want to use the software because they think "Oh, TypeScript, I don't know that, so I won't use this."

**Comment by rakusan2** [comment]
I can see what you mean.
My master branch currently contains the error handling code and will soon contain the following additional changes:
1. The change from using `.innerHTML` property to data of the internal text node
    * this property likes to recreate the element which causes problems that are difficult to debug
2. Your `onValueChanged()` method is getting long so I will be spreading out the switch block into multiple `NetworkTables.addKeyListener()`
    * Based on the NetworkTable code, the global listener is always caled before the key listener

**Comment by ErikBoesen** [comment]
Just temporarily merging to a separate branch so I can play with some things. I plan to merge into master, if for no other reason than that I can't stand raw JS.

**Pull request merged**
