### PR TITLE
Update README, fix spelling, and add JSDoc styled type annotations

### PR DESCRIPTION
**Pull request by rakusan2**
With this I have:
* taken care of #28 
* Updated minimum FRC-NT-Client version to solve #23 
* added type annotations discretely into comments for those with editors that support typescript without influencing those that have not used typescript
* Updated the name of the builder

I have not updated the electron-builder since the current version has issues installing on my system

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Please pull from upstream to resolve merge conflicts. Otherwise, this looks good.

**Comment by rakusan2** [comment]
It is showing me that there are no merge conflicts.
I have also not expected any since when I started this change couple of days ago, I had pulled from upstream

**Comment by ErikBoesen** [comment]
Question: What's the purpose of having `tsconfig.json` here?

**Comment by rakusan2** [comment]
`tsconfig.json` is there from when I was thinking of fully enabling typescript in `.js` files
That ended in lots of error appearing that I was unable to fix
So the file can now be deleted since the type definition files will continue to be used by a typescript enabled editor without it

**Pull request merged**
